server:
  port: 8080

spring:
  application:
    name: ai-pr-review-backend
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/ai_code_review?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:ai_review_user}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
github:
  token: ${GITHUB_TOKEN:}

ai:
  base-url: ${AI_BASE_URL:https://api.deepseek.com}
  api-key: ${AI_API_KEY:}
  model-name: ${AI_MODEL_NAME:deepseek-chat}
  temperature: ${AI_TEMPERATURE:0.2}
  max-tokens: 3000
